name: Build

on: [push]

env:
  TEST_FOLDER: .github/test

jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux

    steps:
    - name: install dependencies
      uses: mstksg/get-package@v1
      with:
        brew: automake
        apt-get: libc6-dbg gdb
    - name: checkout project
      uses: actions/checkout@v1
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: build
      run: make
    - name: try ls -l
      run: ./vg-in-place ls -l
    - name: build regression tests
      run: make check
    - name: create artifacts folder
      run: mkdir -p ${{ env.TEST_FOLDER }}/outputs
    - name: regression tests
      run: make regtest || true
      env:
        REGTEST_ARGS: --results-to=${{ env.TEST_FOLDER }}/results.txt
    - name: trim results
      run: sed '1,2d;$d' ${{ env.TEST_FOLDER }}/results.txt > results-tests.txt
    - name: copy failing test outputs
      run: cat ${{ env.TEST_FOLDER }}/results.txt | sed 1,2d | cut -f 1 -d' ' | xargs -L1 -I % sh -c 'cp %.*.diff* ${{ env.TEST_FOLDER }}/outputs/'
    - name: calculate difference between tests
      uses: LouisBrunner/diff-action@v0.1.1
      with:
        old: .github/${{ env.PLATFORM }}-expected.txt
        new: results-tests.txt
        mode: deletion
        tolerance: same
        output: ${{ env.TEST_FOLDER }}/results.diff
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ env.PLATFORM }}
        notify_check: true
        notify_issue: true
    - name: upload artifacts
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-results-${{ env.PLATFORM }}
        path: ${{ env.TEST_FOLDER }}/
